### ISSUE TITLE
стандартний список льготніків

### ISSUE THREAD

**Issue by Diffurius** [romanm/am-msg001#1]
стандартний список льготніків

**Comment by Diffurius** [comment]
поки закриваю, список потім змінимо

**Comment by romanm** [comment]
це можна робити прямо тут
https://github.com/romanm/am-msg001/blob/master/src/main/resources/static/f/config/payment_privilege.json

**Comment by Diffurius** [comment]
треба роз'яснення, файлу немає(чи він вже є в проекті?)

**Comment by romanm** [comment]
> треба роз'яснення, файлу немає(чи він вже є в проекті?)
файл

../am-ris001/h2-server/site_config.json
шлях до файла прописаний в 
src/main/resources/a2.properties 
в полі
am.configDir:
Конфігураційний файл винесений за межі папки проекту як і сама база даних
тому що всі файли в папці проекту можуть видалятись і змінюватись 
командами git при загрузці нової версії програми
