### ISSUE TITLE
оновлення поля "тип дослідження", "Лікар"

### ISSUE THREAD

**Issue by Diffurius** [romanm/am-msg001#11]
Може змінюватись в основній базі.

**Comment by Diffurius** [comment]
Пропозиція: " можливо в майбутньому, поле "тип дослідження" зробити довідником(прайсом)"

**Comment by romanm** [comment]
Це зроблено з самого початку, в діалозі запису ціни справа показується перелік введених раніше цін на дослідженя на яке прийшов пацієнт.
Користуйтесь, вчіть персонал, пишіть коментарі

**Comment by Diffurius** [comment]
Треба видаляти ті які були змінені в базі, впливає на кількість досліджень і пацієнтів.

**Comment by Diffurius** [comment]
1 день на тестування, враховуючи що кнопка є
