### ISSUE TITLE
роздупленя здуплених досліджень в одному запису 

### ISSUE THREAD

**Issue by romanm** [romanm/am-msg001#18]
Записи з комою в досліджені розщіпити по комі і записати як декілька досліджень на один і той самий час в одній секунді розділений інтервалами в мікросекундах.

**Comment by Diffurius** [comment]
У мне з'явилася ідея. При "роздуплені" видаляти запис з декількома дослідженнями, але враховувати його при де дуплікації.

**Comment by Diffurius** [comment]
більше не потрібно
