### ISSUE TITLE
Вибірка за полями 

### ISSUE THREAD

**Issue by Diffurius** [romanm/am-msg001#3]
Вибірка за полями  
ціна, тип оплати, тип льготи

**Comment by Diffurius** [comment]
або навіть  краще формування exel, з конкретним проміжком часу с усіма полями.

**Comment by romanm** [comment]
exel для пошуку і виборки це абсурд

**Comment by romanm** [comment]
> Вибірка за полями
> ціна, тип оплати, тип льготи

- з'ясуй чи є прив'язка процента знижки до типу льгот
- для виборки по платежу якщо будуть надані  фіксовані групи, я включу їх в випадаючий список для зручності

**Comment by Diffurius** [comment]
> > Вибірка за полями
> > ціна, тип оплати, тип льготи
> 
> * з'ясуй чи є прив'язка процента знижки до типу льгот
> * для виборки по платежу якщо будуть надані  фіксовані групи, я включу їх в випадаючий список для зручності

>*exel не для пошуку, а для створення документу будь-яким набором даних(наприклад для пересилки людям які не мають доступу до бази)

>*прив'язка є.
>* вибірку нададуть

**Comment by Diffurius** [comment]
Закриваю працює, специфіку буду писати окремо.
